# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Tipo 1', 'Tipo 1'), ('Tipo 2', 'Tipo 2')], default='Tipo 1', max_length=7)),
                ('nombre', models.CharField(max_length=50)),
                ('persona', models.CharField(max_length=100)),
                ('caracter', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=7)),
                ('cupos', models.IntegerField(default=0)),
                ('informacion', models.TextField()),
                ('imagen', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'ordering': ['fecha_inicio', 'hora_inicio'],
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=50)),
                ('foto', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, default=None, help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', null=True, upload_to=b'')),
                ('actividades', models.ManyToManyField(to='Aplicacion.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Asistente_Ingresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresado', models.BooleanField(default=False)),
                ('traduccion', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actividad')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('respondida', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actividad')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('logo', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default='Publico', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('localizacion', geoposition.fields.GeopositionField(default='4.7,-74', max_length=42)),
                ('logo', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Evento')),
            ],
            options={
                'verbose_name': 'Informacion del evento',
                'verbose_name_plural': 'Informacion del Evento',
            },
        ),
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(help_text='Soporta archivos en formato DOCX,PDF,PPT,XML', upload_to=b'')),
                ('descripcion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('logo', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
                ('stand', models.IntegerField()),
                ('hipervinculo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Evento')),
            ],
            options={
                'verbose_name': 'Muestra Comercial',
                'verbose_name_plural': 'Muestras Comerciales',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=50)),
                ('votos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('baner', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
                ('hipervinculo', models.URLField()),
                ('logo', models.ImageField(help_text='Soporta archivos en formato JPEG,JPG,PNG,BMP', upload_to=b'')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Soporte Tecnico'), (3, 'Punto de control')])),
                ('asistente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Asistente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Evento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('actividades', models.ManyToManyField(related_name='actividades', to='Aplicacion.Actividad')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Evento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Control',
                'verbose_name_plural': 'Puntos de Control',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Pregunta'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='patrocinadores',
            field=models.ManyToManyField(to='Aplicacion.Patrocinador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='servicios',
            field=models.ManyToManyField(to='Aplicacion.Servicio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_asociado', to='Aplicacion.Evento'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Categoria'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Empresa'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='eventos',
            field=models.ManyToManyField(to='Aplicacion.Evento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='categorias',
            field=models.ManyToManyField(to='Aplicacion.Categoria'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Evento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='servicios',
            field=models.ManyToManyField(to='Aplicacion.Servicio'),
        ),
        migrations.CreateModel(
            name='AvanceAgenda',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('Aplicacion.actividad',),
        ),
        migrations.CreateModel(
            name='ValidarAsistente',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('Aplicacion.asistente',),
        ),
    ]
