# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_auto_20170124_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('Ingles', 'Ingles'), ('Espanol', 'Espanol'), ('Frances', 'Frances')], default='Ingles', max_length=15)),
                ('url_android', models.CharField(max_length=80)),
                ('url_ios', models.CharField(max_length=80)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Actividad')),
            ],
        ),
    ]
